version: "3"
services:

  db:
    image: mysql/mysql-server:5.7
    container_name: db-mysql
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: Pn123456
      MYSQL_ROOT_PASSWORD: Pn123456
      MYSQL_DATABASE: Testdb
    ports:
      - 3306:3306
    networks:
      - mysql_app

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Pn123456
    ports:
      - 8080:8080
    networks:
      - mysql_app

networks:
  mysql_app:
    driver: bridge

